name: 'Flyway Migrations Checks Action'
description: 'A GitHub Action to run pre-deployment checks on your Flyway migrations'
author: 'Redgate'

branding:
  icon: 'database'
  color: 'red'

inputs:
  target-environment:
    description: 'Target database to check'
    required: false
    default: 'default'
  target-url:
    description: 'JDBC URL for the target database to check'
    required: false
  target-user:
    description: 'Database user for the target database to check'
    required: false
  target-password:
    description: 'Database password for the target database to check'
    required: false
  target-schemas:
    description: 'Comma-separated list of schemas for the target database'
    required: false
  target-migration-version:
    description: 'Migrate up to this version for dry run'
    required: false
  cherry-pick:
    description: 'Comma-separated list of migration versions to include'
    required: false
  fail-on-code-review:
    description: 'Whether to fail the action when code review violations are found'
    required: false
    default: 'true'
  fail-on-drift:
    description: 'Whether to fail the action when drift is detected'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for Flyway'
    required: false
  extra-args:
    description: 'Additional Flyway CLI arguments (e.g. -sqlMigrationPrefix=M)'
    required: false

runs:
  using: 'node24'
  main: 'dist/index.js'
