name: 'Flyway Migrations Checks Action'
description: 'A GitHub Action to run pre-deployment checks on your Flyway migrations'
author: 'Redgate'

branding:
  icon: 'database'
  color: 'red'

inputs:
  target-environment:
    description: 'Target database to check'
    required: false
    default: 'default'
  target-url:
    description: 'JDBC URL for the target database to check'
    required: false
  target-user:
    description: 'Database user for the target database to check'
    required: false
  target-password:
    description: 'Database password for the target database to check'
    required: false
  target-schemas:
    description: 'Comma-separated list of schemas for the target database'
    required: false
  target-migration-version:
    description: 'Migrate up to this version for dry run'
    required: false
  cherry-pick:
    description: 'Comma-separated list of migration versions to include'
    required: false
  build-environment:
    description: 'Build database for generating a deployment changes report'
    required: false
  build-url:
    description: 'JDBC URL for the build database'
    required: false
  build-user:
    description: 'Database user for the build database'
    required: false
  build-password:
    description: 'Database password for the build database'
    required: false
  build-schemas:
    description: 'Comma-separated list of schemas for the build database'
    required: false
  build-ok-to-erase:
    description: 'Allow Flyway to erase the build database. This will delete all schema and data objects'
    required: false
    default: 'false'
  skip-code-review:
    description: 'Skip the code review check'
    required: false
    default: 'false'
  skip-drift-check:
    description: 'Skip the drift check'
    required: false
    default: 'false'
  skip-deployment-changes-report:
    description: 'Skip the deployment changes report'
    required: false
    default: 'false'
  skip-deployment-script-review:
    description: 'Skip the deployment script review (dry run)'
    required: false
    default: 'false'
  fail-on-code-review:
    description: 'Whether to fail the action when code review violations are found'
    required: false
    default: 'true'
  fail-on-drift:
    description: 'Whether to fail the action when drift is detected'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for Flyway'
    required: false
  extra-args:
    description: 'Additional Flyway CLI arguments (e.g. -sqlMigrationPrefix=M)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Run Flyway checks
      run: node "${{ github.action_path }}/dist/index.js"
      shell: bash
      env:
        INPUT_TARGET-ENVIRONMENT: ${{ inputs.target-environment }}
        INPUT_TARGET-URL: ${{ inputs.target-url }}
        INPUT_TARGET-USER: ${{ inputs.target-user }}
        INPUT_TARGET-PASSWORD: ${{ inputs.target-password }}
        INPUT_TARGET-SCHEMAS: ${{ inputs.target-schemas }}
        INPUT_TARGET-MIGRATION-VERSION: ${{ inputs.target-migration-version }}
        INPUT_CHERRY-PICK: ${{ inputs.cherry-pick }}
        INPUT_BUILD-ENVIRONMENT: ${{ inputs.build-environment }}
        INPUT_BUILD-URL: ${{ inputs.build-url }}
        INPUT_BUILD-USER: ${{ inputs.build-user }}
        INPUT_BUILD-PASSWORD: ${{ inputs.build-password }}
        INPUT_BUILD-SCHEMAS: ${{ inputs.build-schemas }}
        INPUT_BUILD-OK-TO-ERASE: ${{ inputs.build-ok-to-erase }}
        INPUT_SKIP-CODE-REVIEW: ${{ inputs.skip-code-review }}
        INPUT_SKIP-DRIFT-CHECK: ${{ inputs.skip-drift-check }}
        INPUT_SKIP-DEPLOYMENT-CHANGES-REPORT: ${{ inputs.skip-deployment-changes-report }}
        INPUT_SKIP-DEPLOYMENT-SCRIPT-REVIEW: ${{ inputs.skip-deployment-script-review }}
        INPUT_FAIL-ON-CODE-REVIEW: ${{ inputs.fail-on-code-review }}
        INPUT_FAIL-ON-DRIFT: ${{ inputs.fail-on-drift }}
        INPUT_WORKING-DIRECTORY: ${{ inputs.working-directory }}
        INPUT_EXTRA-ARGS: ${{ inputs.extra-args }}

    - name: Upload HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: flyway-report
        path: ${{ inputs.working-directory && format('{0}/report.html', inputs.working-directory) || 'report.html' }}
        if-no-files-found: ignore
