name: 'Flyway Migrations Checks Action'
description: 'A GitHub Action to run pre-deployment checks on your Flyway migrations'
author: 'Redgate'

branding:
  icon: 'database'
  color: 'red'

inputs:
  target-environment:
    description: 'Target database environment name'
    required: false
  target-url:
    description: 'JDBC URL for the target database'
    required: false
  target-user:
    description: 'Database user for the target database'
    required: false
  target-password:
    description: 'Database password for the target database'
    required: false
  target-schemas:
    description: 'Comma-separated list of schemas for the target database'
    required: false
  build-environment:
    description: 'Named environment for the build database, used by Flyway to generate comparison reports. See https://documentation.red-gate.com/flyway/flyway-concepts/environments/shadow-and-build-environments'
    required: false
  build-url:
    description: 'JDBC URL for the build database. Used as an alternative to build-environment for inline configuration. See https://documentation.red-gate.com/flyway/flyway-concepts/environments/shadow-and-build-environments'
    required: false
  build-user:
    description: 'Database user for the build database. Used with build-url for inline configuration. See https://documentation.red-gate.com/flyway/flyway-concepts/environments/shadow-and-build-environments'
    required: false
  build-password:
    description: 'Database password for the build database. Used with build-url for inline configuration. See https://documentation.red-gate.com/flyway/flyway-concepts/environments/shadow-and-build-environments'
    required: false
  build-schemas:
    description: 'Comma-separated list of schemas for the build database. Used with build-url for inline configuration. See https://documentation.red-gate.com/flyway/flyway-concepts/environments/shadow-and-build-environments'
    required: false
  generate-report:
    description: 'Generate a deployment report (requires build environment)'
    required: false
    default: 'true'
  fail-on-drift:
    description: 'Fail the action if drift is detected'
    required: false
    default: 'true'
  fail-on-code-review:
    description: 'Fail the action if code review violations are found'
    required: false
    default: 'true'
  target-migration-version:
    description: 'Target migration version for deployment report and dry run'
    required: false
  cherry-pick:
    description: 'Comma-separated list of migration versions to include'
    required: false
  working-directory:
    description: 'Working directory for Flyway'
    required: false
  extra-args:
    description: 'Additional arguments to pass to Flyway'
    required: false

runs:
  using: 'node24'
  main: 'dist/index.js'
