name: 'Flyway Migrations Checks Action'
description: 'A GitHub Action to run pre-deployment checks on your Flyway migrations'
author: 'Redgate'

branding:
  icon: 'database'
  color: 'red'

inputs:
  target-environment:
    description: 'Target database to check'
    required: false
    default: 'default'
  target-url:
    description: 'JDBC URL for the target database to check'
    required: false
  target-user:
    description: 'Database user for the target database to check'
    required: false
  target-password:
    description: 'Database password for the target database to check'
    required: false
  target-schemas:
    description: 'Comma-separated list of schemas for the target database'
    required: false
  target-migration-version:
    description: 'Migrate up to this version for dry run'
    required: false
  cherry-pick:
    description: 'Comma-separated list of migration versions to include'
    required: false
  build-environment:
    description: 'Build database for generating a deployment changes report'
    required: false
  build-url:
    description: 'JDBC URL for the build database'
    required: false
  build-user:
    description: 'Database user for the build database'
    required: false
  build-password:
    description: 'Database password for the build database'
    required: false
  build-schemas:
    description: 'Comma-separated list of schemas for the build database'
    required: false
  build-ok-to-erase:
    description: 'Allow Flyway to erase the build database. This will delete all schema and data objects'
    required: false
    default: 'false'
  skip-code-review:
    description: 'Skip the code review check'
    required: false
    default: 'false'
  skip-drift-check:
    description: 'Skip the drift check'
    required: false
    default: 'false'
  skip-deployment-changes-report:
    description: 'Skip the deployment changes report'
    required: false
    default: 'false'
  skip-deployment-script-review:
    description: 'Skip the deployment script review (dry run)'
    required: false
    default: 'false'
  fail-on-code-review:
    description: 'Whether to fail the action when code review violations are found'
    required: false
    default: 'true'
  fail-on-drift:
    description: 'Whether to fail the action when drift is detected'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for Flyway'
    required: false
  extra-args:
    description: 'Additional Flyway CLI arguments (e.g. -sqlMigrationPrefix=M)'
    required: false

outputs:
  exit-code:
    description: 'Flyway exit code'
  drift-detected:
    description: 'Whether drift was detected (empty if skipped)'
  changed-object-count:
    description: 'Number of changed objects in the deployment (empty if skipped)'
  code-violation-count:
    description: 'Number of code review violations found (empty if skipped)'
  code-violation-codes:
    description: 'Comma-separated list of code review violation codes (empty if skipped)'

runs:
  using: 'node24'
  main: 'dist/index.js'
