name: 'Flyway Migrate'
description: 'Run Flyway migrate command to apply database migrations'
author: 'Redgate'

branding:
  icon: 'database'
  color: 'blue'

inputs:
  url:
    description: 'JDBC URL for the database connection'
    required: false
  user:
    description: 'Database user for the connection'
    required: false
  password:
    description: 'Database password for the connection'
    required: false
  environment:
    description: 'Flyway TOML environment name'
    required: false
  target:
    description: 'Migrate up to this version'
    required: false
  cherry-pick:
    description: 'Comma-separated list of migration versions to apply'
    required: false
  baseline-on-migrate:
    description: 'Automatically baseline on first deploy'
    required: false
    default: 'true'
  save-snapshot:
    description: 'Embed snapshot for drift checks'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for Flyway execution'
    required: false
  extra-args:
    description: 'Additional arguments to pass to Flyway'
    required: false

outputs:
  exit-code:
    description: 'Flyway command exit code'
  flyway-version:
    description: 'Version of Flyway that was used'
  migrations-applied:
    description: 'Number of migrations applied'
  schema-version:
    description: 'Schema version after migration'

runs:
  using: 'node24'
  main: 'dist/index.cjs'
