name: 'Flyway Migrate'
description: 'Run Flyway migrate command to apply database migrations'
author: 'Redgate'

branding:
  icon: 'database'
  color: 'red'

inputs:
  # Connection
  url:
    description: 'JDBC URL for the database connection'
    required: true
  user:
    description: 'Database user for the connection'
    required: false
  password:
    description: 'Database password for the connection'
    required: false

  # Configuration
  config-files:
    description: 'Comma-separated paths to Flyway configuration files'
    required: false
  working-directory:
    description: 'Working directory for Flyway execution'
    required: false

  # Escape hatch
  extra-args:
    description: 'Additional arguments to pass to Flyway'
    required: false

outputs:
  exit-code:
    description: 'Flyway command exit code'
  migrations-applied:
    description: 'Number of migrations applied'
  schema-version:
    description: 'Schema version after migration'

runs:
  using: 'node24'
  main: 'dist/index.cjs'
